defaults: &defaults
  host: localhost
  port: 6379
  password:

development:
  <<: *defaults

test: &test
  <<: *defaults

bvt:
  <<: *defaults

production:
  host: 192.168.100.10

cucumber:
  <<: *test